name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Grant execution permission for gradlew
      run: chmod +x ./gradlew
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    - name: Build APK
      run: ./gradlew assembleDebug  # 这里也可以替换为 assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-APK
        path: app/build/outputs/apk/debug/*.apk
