name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Grant execution permission for gradlew
      run: chmod +x ./gradlew

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Run Lint
      run: ./gradlew lint

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-APK
        path: app/build/outputs/apk/debug/*.apk
