name: Build APK and Release

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当对 main 分支创建拉取请求时触发

jobs:
  build:
    name: Build Android App and Upload to Releases
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu Runner

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 授予 gradlew 执行权限
      - name: Grant execution permission for gradlew
        run: chmod +x ./gradlew

      # 3. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 4. 设置 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33

      # 5. 安装构建工具
      - name: Install build-tools
        run: sdkmanager "build-tools;33.0.2"

      # 6. 设置签名的 keystore 文件
      - name: Set up keystore file
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > /tmp/keystore.jks
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      # 7. 构建 Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 8. 构建 Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease -PKEYSTORE_FILE=/tmp/keystore.jks -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      # 9. 创建 Git 标签
      - name: Create a Git tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # 创建一个以时间戳命名的标签，例如 v20241122063905
          git tag $TAG_NAME
          git push origin $TAG_NAME  # 推送标签到 GitHub 仓库

      # 10. 上传 Debug APK 到 GitHub Releases
      - name: Upload Debug APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 11. 上传 Release APK 到 GitHub Releases
      - name: Upload Release APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
