name: Build APK

on:
  push:
    branches:
      - main  # 触发构建的分支
  pull_request:
    branches:
      - main  # 拉取请求时触发构建

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级到最新版本支持 Node.js 20

    - name: Grant execution permission for gradlew
      run: chmod +x ./gradlew  # 为 gradlew 文件添加执行权限

    - name: Setup JDK
      uses: actions/setup-java@v4  # 升级到支持 Node.js 20 的版本
      with:
        distribution: 'zulu'
        java-version: '11'  # 使用 JDK 11

    - name: Install Android SDK and Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32stdc++6 lib32z1
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"  # 安装 SDK 和 Build Tools

    - name: Build APK
      run: ./gradlew assembleDebug assembleRelease  # 同时构建 Debug 和 Release APK

    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-APKs
        path: |
          app/build/outputs/apk/debug/*.apk  # 上传 debug 版本的 APK
          app/build/outputs/apk/release/*.apk  # 上传 release 版本的 APK
