name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # 触发条件：推送以 v 开头的标签，表示发布版本

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 设置最大构建时间为 120 分钟

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 为 gradlew 文件授予执行权限
      - name: Grant execution permission for gradlew
        run: chmod +x ./gradlew

      # 3. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 4. 设置 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34  # 设置目标 API 版本
          build-tools: "34.0.0"  # 设置 Build Tools 版本

      # 5. 自动接受 Android SDK 许可证
      - name: Accept licenses
        run: yes | sdkmanager --licenses || true

      # 6. 解码 Keystore 文件并保存到 /tmp
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > /tmp/keystore.jks

      # 7. 构建 Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=/tmp/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # 8. 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}  # 使用当前的标签作为版本号
          release_name: Release ${{ github.ref }}  # 使用标签作为 Release 名称
          draft: false  # 发布正式版本
          prerelease: false  # 非预发布版本

      # 9. 上传 Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk  # 构建输出 APK 路径
          asset_name: app-release.apk  # 上传的 APK 文件名
          asset_content_type: application/vnd.android.package-archive  # 设置内容类型为 APK
